# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/src/messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/src/messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63ommon/src/messages.proto\"\x86\x01\n\x13OrchestratorCommand\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .OrchestratorCommand.CommandType\x12\x12\n\nvault_path\x18\x02 \x01(\t\"+\n\x0b\x43ommandType\x12\x08\n\x04PING\x10\x00\x12\x12\n\x0eGENERATE_TASKS\x10\x01\"\x93\x01\n\x12OrchestratorStatus\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\x12\x36\n\x0e\x63urrent_status\x18\x02 \x01(\x0e\x32\x1e.OrchestratorStatus.StatusType\"3\n\nStatusType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.src.messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORCHESTRATORCOMMAND']._serialized_start=30
  _globals['_ORCHESTRATORCOMMAND']._serialized_end=164
  _globals['_ORCHESTRATORCOMMAND_COMMANDTYPE']._serialized_start=121
  _globals['_ORCHESTRATORCOMMAND_COMMANDTYPE']._serialized_end=164
  _globals['_ORCHESTRATORSTATUS']._serialized_start=167
  _globals['_ORCHESTRATORSTATUS']._serialized_end=314
  _globals['_ORCHESTRATORSTATUS_STATUSTYPE']._serialized_start=263
  _globals['_ORCHESTRATORSTATUS_STATUSTYPE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
