# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\x86\x01\n\x13OrchestratorCommand\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .OrchestratorCommand.CommandType\x12\x12\n\nvault_path\x18\x02 \x01(\t\"+\n\x0b\x43ommandType\x12\x08\n\x04PING\x10\x00\x12\x12\n\x0eGENERATE_TASKS\x10\x01\"\x93\x01\n\x12OrchestratorStatus\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\x12\x36\n\x0e\x63urrent_status\x18\x02 \x01(\x0e\x32\x1e.OrchestratorStatus.StatusType\"3\n\nStatusType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x62\x06proto3')



_ORCHESTRATORCOMMAND = DESCRIPTOR.message_types_by_name['OrchestratorCommand']
_ORCHESTRATORSTATUS = DESCRIPTOR.message_types_by_name['OrchestratorStatus']
_ORCHESTRATORCOMMAND_COMMANDTYPE = _ORCHESTRATORCOMMAND.enum_types_by_name['CommandType']
_ORCHESTRATORSTATUS_STATUSTYPE = _ORCHESTRATORSTATUS.enum_types_by_name['StatusType']
OrchestratorCommand = _reflection.GeneratedProtocolMessageType('OrchestratorCommand', (_message.Message,), {
  'DESCRIPTOR' : _ORCHESTRATORCOMMAND,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:OrchestratorCommand)
  })
_sym_db.RegisterMessage(OrchestratorCommand)

OrchestratorStatus = _reflection.GeneratedProtocolMessageType('OrchestratorStatus', (_message.Message,), {
  'DESCRIPTOR' : _ORCHESTRATORSTATUS,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:OrchestratorStatus)
  })
_sym_db.RegisterMessage(OrchestratorStatus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ORCHESTRATORCOMMAND._serialized_start=19
  _ORCHESTRATORCOMMAND._serialized_end=153
  _ORCHESTRATORCOMMAND_COMMANDTYPE._serialized_start=110
  _ORCHESTRATORCOMMAND_COMMANDTYPE._serialized_end=153
  _ORCHESTRATORSTATUS._serialized_start=156
  _ORCHESTRATORSTATUS._serialized_end=303
  _ORCHESTRATORSTATUS_STATUSTYPE._serialized_start=252
  _ORCHESTRATORSTATUS_STATUSTYPE._serialized_end=303
# @@protoc_insertion_point(module_scope)
